apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-lcs-lab5
  region: us-east-1

iam:
  serviceRoleARN: arn:aws:iam::<AWS-ACCOUNT-ID>:role/LabRole
  withOIDC: false

managedNodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 2
    minSize: 2
    maxSize: 2
    iam:
      instanceRoleARN: arn:aws:iam::<AWS-ACCOUNT-ID>:role/LabRole
