apiVersion: batch/v1
kind: Job
metadata:
  name: nfs-content-copy-job
spec:
  template:
    spec:
      containers:
      - name: alpine
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            mkdir -p /source
            echo "Hello NFS!" > /source/index.html
            
            cp /source/* /mnt/nfs/ 
        volumeMounts:
        - name: nfs-storage
          mountPath: /mnt/nfs
      restartPolicy: Never
      volumes:
      - name: nfs-storage
        persistentVolumeClaim:
          claimName: nfs-pvc
  backoffLimit: 4
